apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
  - http:
      paths:
      - path: /ng-zorro-spa/
        pathType: Prefix
        backend:
          serviceName: ng-zorro-spa-service
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ng-zorro-spa-service
spec:
  type: ClusterIP
  selector:
    component: ng-zorro-spa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-zorro-spa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ng-zorro-spa
  template:
    metadata:
      labels:
        component: ng-zorro-spa
    spec:
      containers:
        - name: ng-zorro-spa
          image: inimeve/ng-zorro-spa:0.0.1_alpha5
          imagePullPolicy: Never
          ports:
            - containerPort: 80